
import { Node, Edge } from '@xyflow/react';

export interface DmxValue {
  ch: number;
  val: number;
}

export enum ConnectionStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING'
}

/**
 * Configuration for audio-reactive parameters per channel/fixture
 */
export interface AudioReactiveConfig {
  enabled: boolean;
  autoMode: boolean;
  frequency: 'low' | 'mid' | 'high';
  threshold: number;
  sensitivity: number;
  decay: number;
}

/**
 * Representation of a lighting preset generated by Gemini
 */
export interface Preset {
  name: string;
  description: string;
  channels: DmxValue[];
}

export interface FixtureConfig {
  id: string;
  type: 'dimmer' | 'led_par' | 'spider' | 'spark' | 'laser';
  name: string;
  startChannel: number;
  group: string;
  values: number[]; 
  manualValues: number[]; 
  mutes: boolean[]; 
  audioConfigs: AudioReactiveConfig[];
}

export type MixingStrategy = 'sum' | 'max' | 'avg' | 'last';

export interface NodeData {
  label: string;
  type: string;
  params?: any;
  mixing?: MixingStrategy;
  values?: number[]; 
  onChange?: (nodeId: string, channelIdx: number, val: number) => void;
  onParamChange?: (nodeId: string, key: string, val: any) => void;
  onAudioLevelsUpdate?: (nodeId: string, levels: { low: number, mid: number, high: number }) => void;
  color?: string;
  [key: string]: unknown;
}

export interface EdgeData {
  onDelete?: (id: string) => void;
  [key: string]: unknown;
}

export type LuminaNode = Node<NodeData>;
export type LuminaEdge = Edge<EdgeData>;
